# Generated by Django 4.2.17 on 2024-12-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggy_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Enter the choices for the Dropdown or CheckBox', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter the Question', max_length=200),
        ),
    ]
