# Generated by Django 4.2.17 on 2024-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buggy_forms', '0004_form_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
